export const ACTION_TYPES = {
    FETCH_CRYPTO_LIST_DATA: 'FETCH_CRYPTO_LIST_DATA',
    FETCH_CRYPTO_HISTORICAL_DATA: 'FETCH_CRYPTO_HISTORICAL_DATA',
    SET_CURRENTLY_SELECTED_COIN: 'SET_CURRENTLY_SELECTED_COIN',
    SET_SEARCH_CRYPTO_LIST_VALUE: 'SET_SEARCH_CRYPTO_LIST_VALUE'
};