export const ACTION_TYPES = {
    FETCH_INVOICE_LIST: 'FETCH_INVOICE_LIST',
    FETCH_DOCUMENT: 'FETCH_DOCUMENT',
    UPDATE_CURRENTLY_SELCTED_DOCUMENT: 'UPDATE_CURRENTLY_SELCTED_DOCUMENT',
    SET_DOCMENT_FETCH_ERROR: 'SET_DOCMENT_FETCH_ERROR',
    SET_SEARCH_VALUE: 'SET_SEARCH_VALUE',
    SET_INVOICE_LIST_LOADING: 'SET_INVOICE_LIST_LOADING',
    SET_CURRENT_DOCUMENT_LOADING: 'SET_CURRENT_DOCUMENT_LOADING',
    SET_FORM_DATA: 'SET_FORM_DATA',
    REMOVE_FORM_DATA: 'REMOVE_FORM_DATA'
};
