export const ACTION_TYPES = {
    FETCH_INVOICE_LIST: 'FETCH_INVOICE_LIST',
    FETCH_DOCUMENT: 'FETCH_DOCUMENT',
    UPDATE_CURRENTLY_SELCTED_DOCUMENT: 'UPDATE_CURRENTLY_SELCTED_DOCUMENT',
    SET_DOCMENT_FETCH_ERROR: 'SET_DOCMENT_FETCH_ERROR'
};
